version: '3.7'
services:
  calibre:
    image: linuxserver/calibre:latest
    container_name: calibre
    hostname: calibre
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../Data/books:/books
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - GUAC_USER=calibre
      - GUAC_PASS=5f4dcc3b5aa765d61d8327deb882cf99
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    hostname: calibre-web
    restart: unless-stopped
    volumes:
      - ../Data/config:/config
      - ../Data/books:/books
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.calibre-web.rule=Host(`localhost`)"
      - "traefik.http.routers.calibre-web.entrypoints=web-secure"
      - "traefik.http.routers.calibre-web.middlewares=default-headers@file"
      - "traefik.http.routers.calibre-web.service=calibre-web"
      - "traefik.http.routers.calibre-web.tls=true"
      - "traefik.http.services.calibre-web.loadbalancer.server.port=8083"
